eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: EVENTS
          uri: lb://EVENTS
          predicates:
            - Path=/api/events
        - id: NOTIFICATIONS
          uri: lb://NOTIFICATIONS
          predicates:
            - Path=/api/notifications , /websocket
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service

      - url: /event-service/v3/api-docs
        name: Event Service
        primaryName: Event Service

      - url: /notification-service/v3/api-docs
        name: Notification Service
        primaryName: Notification Service            

server:
  port: 8082
